# Generated by Django 5.0.2 on 2024-03-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="card_id", new_name="cart_id",
        ),
    ]
